openapi: 3.0.0
info:
  version: 1.0.0
  title: BookIT
  description: Booking rooms at fictional university department called the Department of Infographics and Trivia (IT).
servers:
  - url: /v1

components:
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
        
    404NotFound:
      description: Not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string

    401Unauthorized:
      description: Issue with authentication credentials
      headers:
        WWW_Authenticate:
          schema:
            type: string
  
#"Basic authentication is a simple authentication scheme built into the HTTP protocol. The client sends HTTP requests with the Authorization header that contains the word Basic word followed by a space and a base64-encoded string username:password."
#Recieved from: https://swagger.io/docs/specification/authentication/basic-authentication/

#It would check if you are either admin or staff based on the user credentials (username (which is the user-id) and password) 
  securitySchemes:
    basicAuth:    
      type: http
      scheme: basic

  links:
    GetRoomByRoomNumber:   
      description: ''
      operationId: getRoomNumber
      parameters:
        roomNumber: '$response.body#/room/roomNumber'
    GetBookedRoomByRoomNumber:  
      description: ''
      operationId: getBookedRoomNumber
      parameters:
        roomNumber: '$response.body#/room/booking/roomNumber'

  schemas:
    Room:
      type: object
      properties:
       roomDescription:
        description: "The description of the room, e.g. Lecture theatre"
        type: string
       maxCapacity:
        description: "Maximum capacity of room"
        type: integer
       plan:
        description: "The level the room is on, e.g. 1"
        type: integer
       corridor:
        description: "The corridor the room is on, e.g. A"
        type: string
#Unique
       roomNumber:
        description: "The full room number, e.g. A114"
        type: string
       roomStatus:
          description: "The room status"
          enum:
            - Booked
            - Available

    Booking:
        type: object
        properties:
#roomNumber is what will uniquely identify the room, together with the bookers' name (booker)
         roomNumber:
          description: "Room that the booking relates to"
          type: string
         startTime:
          description: "Start time of the reservation"
          type: string
          format: date-time
         endTime:
          description: "End time of the reservation"
          type: string
          format: date-time
         booker:
          description: "Name of the person who booked the room"
          type: string
         reason:
          description: "The description of the reason using the room"
          type: string
         expectedMaxCapacity:
          description: "Expected max number of people to use the room in this booking"
          type: integer

tags:
- name: "Administrator"
  description: "Managing the rooms"
- name: "User"
  description: "View the availability status of rooms"
- name: "Staff"
  description: "Booking a room"

#An administrator managing the room records (add, remove, edit rooms) 
paths:
  /room:
    post:
      tags:
      - Administrator
      summary: Add room
      security:
      - basicAuth: []
      description: Administrator add a new room
      operationId: addRoom
      responses:
        '200':
          description: Successful
          content:
           application/json:
            schema:
             type: object
             properties:
              roomNumber:
               type: string
               description: Number of the room
#OpenAPI 3.0's links specification, https://swagger.io/docs/specification/links/
          links:
           GetRoomByRoomNumber:  
            description: ''
            operationId: getRoomNumber
            parameters:
             roomNumber: '$response.body#/roomNumber'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'
        '404':
          description: "Not found"


      requestBody:
        description: Create a new room
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'

  /room/{roomNumber}:
    get:
      tags:
      - Administrator
      summary: Get room number
      security:
      - basicAuth: []
      description: Admin get the room number
      operationId: getRoomNumber
      parameters:
       - name: roomNumber
         in: path
         required: true
         schema:
          type: string
      responses:
        '200':
          description: Successfully getting a room number
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Room' 
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'
        '404':
          description: Room number not found 

    patch:
      tags:
      - Administrator
      summary: Edit room
      security:
      - basicAuth: []
      operationId: editRoom
      description: Administrator edit a room
      parameters:
        - name: roomNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Editing a room
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Room'
      responses:
        '200':
          description: Successful with editing a room
          content:
           application/json:
            schema:
             type: object
             properties:
              roomNumber:
               type: string
               description: Number of the room
                  
          links:
           GetRoomByRoomNumber:
             $ref: '#/components/links/GetRoomByRoomNumber'
        '400':
          $ref: '#/components/responses/400Error'
        "404":
          description: "Room number not found"
        '401':
           $ref: '#/components/responses/401Unauthorized'
    delete:
      tags:
      - Administrator
      summary: Remove room
      security:
      - basicAuth: []
      description: Administrator remove a room
      operationId: removeRoom
      parameters:
        - name: roomNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful
          content:
           application/json:
            schema:
             type: object
             properties:
              roomNumber:
               type: string
               description: Number of the room
          links:
           GetRoomByRoomNumber:
             $ref: '#/components/links/GetRoomByRoomNumber'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'
           
#Anybody getting the list of rooms on a specific floor (plan)
  /room/findRoomsOnFloor:
    get:
      tags:
      - User
      summary: Find rooms on floor
      description: Getting the list of rooms on a specific floor.
      operationId: findRoomsOnFloor
      parameters:
        - name: plan
          in: query
          description: Floor levels to filter by
          required: true
          schema:
           type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '400':
          $ref: '#/components/responses/400Error'

#Anybody getting the list of available rooms 
#Anybody getting the list of booked rooms 
#I.e. ?roomStatus=Booked, would return booked
#Filter on booked or available
  /room/status:
    get:
      tags:
      - User
      summary: Status of rooms
      description: User filter rooms based on available and booked rooms.
      operationId: getRooms
      parameters:
      - name: roomStatus
        in: query
        required: true
        schema:
#Rather than entering free text, we want the user to select a pre-defined value
            enum:
            - Available
            - Booked
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
        '400':
          $ref: '#/components/responses/400Error'

#Anybody getting the booking status of a specific room
#Would return status, either available or booked
  /room/status/{roomNumber}:
    get:
      tags:
      - User
      summary: Booking status of room
      description: User get the booking status of a specific room.
      operationId: getBookedRoom
      parameters:
       - name: roomNumber
         in: path
         required: true
         schema:
           type: string
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                  properties:
                   roomStatus:
                    description: "The room status"
                    enum:
                    - Available
                    - Booked
        '400':
          $ref: '#/components/responses/400Error'
        '404':
          description: Room number not found
          
#A staff member requesting to book a room
#The staff member chooses a room with the number they want

#The hypothetical system bookIT only has to do with rooms, so I also specify what the staff books in the URI itself.
  /room/booking/{roomNumber}:
    post:
      tags:
      - Staff
      summary: Request room
      security:
      - basicAuth: []
      description: The staff requesting to book a room
      operationId: bookingRoom
      parameters:
        - name: roomNumber
          in: path
          description: The room number that the staff requests
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful
          content:
           application/json:
            schema:
             type: object
             properties:
              roomNumber:
               type: string
               description: Number of the room
          links:
           GetBookedRoomByRoomNumber:   
            $ref: '#/components/links/GetBookedRoomByRoomNumber'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'
        "404":
          description: "Room number not found"
      requestBody:
        description: Book a room
        required: true
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/Booking'
    get:
      tags:
      - Staff
      summary: Get booked room number
      security:
      - basicAuth: []
      description: Staff get the booked room number
      operationId: getBookedRoomNumber
      parameters:
       - name: roomNumber
         in: path
         required: true
         schema:
          type: string
      responses:
        '200':
          description: Successfully getting a booked room number
          content:
            application/json:
              schema:
                type: array
                items:
                 $ref: '#/components/schemas/Room'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'

#A staff member editing a room they have booked 
    patch:
      tags:
      - Staff
      summary: Edit booked room
      security:
      - basicAuth: []
      description: Staff edit a booked room
      operationId: editBookedRoom
      parameters:
        - name: roomNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Changing a booked room
        required: true
        content:
          application/json:
            schema:
             type: object
             properties:
               startTime:
                description: "Start time of the reservation"
                type: string
                format: date-time
               endTime:
                description: "End time of the reservation"
                type: string
                format: date-time
               booker:
                description: "Name of the person who booked the room"
                type: string
               reason:
                description: "The description of the reason using the room"
                type: string
               expectedMaxCapacity:
                description: "Expected max number of people to use the room in this booking"
                type: integer
      responses:
        '200':
          description: Successful with editing a booked room
          content:
           application/json:
            schema:
             type: object
             properties:
              roomNumber:
               type: string
               description: Number of the room
          links:
           GetBookedRoomByRoomNumber:   
            $ref: '#/components/links/GetBookedRoomByRoomNumber'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'
        "404":
          description: "Booking not found"

#A staff member relinquishing a room they have booked    
    delete:
      tags:
      - Staff
      summary: Relinquish room
      security:
      - basicAuth: []
      description: Relinquishing a room
      operationId: deleteRoom
      parameters:
        - name: roomNumber
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully relinquished a room
          content:
           application/json:
            schema:
             type: object
             properties:
              roomNumber:
               type: string
               description: Number of the room
          links:
           GetBookedRoomByRoomNumber:   
            $ref: '#/components/links/GetBookedRoomByRoomNumber'
        '400':
          $ref: '#/components/responses/400Error'
        '401':
           $ref: '#/components/responses/401Unauthorized'
        "404":
          description: "Room number not found"
