openapi: 3.0.0
info:
  version: 1.0.0
  title: Latte Lounge API
  description: A REST API to GET a cup of cofveve
servers:
  - url: https://latteloun.ge/v1
components:
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  parameters:
    Limit:
      name: limit
      in: query
      description: Limits the number of orders on a page
      schema:
        type: integer
    Offset:
      name: offset
      in: query
      description: Specifies the page number of the orders to be displayed
      schema:
        type: integer
  schemas:
    Order:
      type: object
      required:
        - drink
      properties:
        orderId:
          type: string
        drink:
          type: string
        addition:
          type: string
        status:
          type: string
        cost:
          type: number
        paid:
          type: boolean
          default: false
    Payment:
      type: object
      required:
        - cardNo
        - expires
        - name
        - amount
      properties:
        cardNo:
          type: string
        expires:
          type: string
        name:
          type: string
        amount:
          type: number
paths:
  /order:
    post:
      description: Cashier creates an order for a coffee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drink:
                  type: string
                addition:
                  type: string
                status:
                  type: string
                cost:
                  type: number
                paid:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Successfully created an order
#          content:
#            application/json:
#              schema:
#                type: object
#                properties:
#                  id:
#                    type: integer
#                    format: int64
#                    description: ID of order
#          links:
#            getOrderByID:
#              description: Get ID
#              operationId: getOrderId
#              parameters:
#                orderId: $response.body#/id
        '400':
          $ref: '#/components/responses/400Error'
    get:
      description: Returns a list of orders
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Successfully returned a list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/400Error'
  /order/{orderId}:
    patch:
      description: Amends the order by adding an addition
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Order'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                addition:
                  type: string
      responses:
        '200':
          description: Successfully added an addition
        '400':
          $ref: '#/components/responses/400Error'
          #The order will be released (removed) depending on the status for that order
    delete:
      description: Release the order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successfully deleted an order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/400Error'
  /order/{orderId}/payment:
    post:
      description: Cashier creates a payment for the order
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: Successfully created a payment for the order
        '400':
          $ref: '#/components/responses/400Error'
    get:
      description: Checks if the order is paid
#      operationId: getOrderId
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: object
            properties:
              orderId:
                type: string
              paid:
                type: boolean
      responses:
        '200':
          description: Successfully returned an order
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                   type: string
                  paid:
                   type: boolean
        '400':
          $ref: '#/components/responses/400Error'
          #The status of the order can i.e. be changed to prepared, which will make it an open order, served or cancelled.
          #If a customer cancel the order, paid will also be changed to false as they will get their money back.
  /order/{orderId}/payment/status:
    patch:
      description: Changes the status of the order to being prepared
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Order'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                paid:
                  type: boolean
                  default: true
      responses:
        '200':
          description: Successfully added an addition
        '400':
          $ref: '#/components/responses/400Error'
    get:
      description: Checks if the order is open
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Successfully returned a list of open orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/400Error'
