openapi: 3.0.0
info:
  version: 1.0.0
  title: Latte Lounge API
  description: A REST API to GET a cup of cofveve
servers:
  - url: https://latteloun.ge/v1
#From a life like scenario, it would be strange if barista and cashier wouldn't be able to do the same thing, because they could be the same person.
tags:
  - name: "Barista and cashier"
components:
  responses:
    400BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  parameters:
    Limit:
      name: limit
      in: query
      description: Limits the number of orders on a page
      schema:
        type: integer
    Offset:
      name: offset
      in: query
      description: Specifies the page number of the orders to be displayed
      schema:
        type: integer
  schemas:
    Order:
      type: object
      required:
        - drink
      properties:
        orderId:
          type: string
        drink:
          type: string
        addition:
          type: string
        status:
          type: string
        cost:
          type: number
        paid:
          type: boolean
          default: false
    Payment:
      type: object
      required:
        - cardNo
        - expires
        - name
        - amount
      properties:
        cardNo:
          type: string
        expires:
          type: string
        name:
          type: string
        amount:
          type: number
paths:
  /order:
  # 1. Cashier creates an Order for a coffee (e.g. latte, cappuccino, espresso etc.)
    post:
      tags:
      - "Barista and cashier"
      description: Cashier creates an order for a coffee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drink:
                  type: string
                addition:
                  type: string
                status:
                  type: string
                cost:
                  type: number
                paid:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Successfully created an order
        '400':
          $ref: '#/components/responses/400BadRequest'

  /order/{orderId}:
    # 2. Cashier amends the Order by adding an addition (e.g. extra shot, whipped cream etc.)
    # You want to use patch instead of put as you only want to do some changes to an existing resource, in this case an existing order.
    patch:
      tags:
      - "Barista and cashier"
      description: Amends the order by adding an addition
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                addition:
                  type: string
      responses:
        '200':
          description: Successfully added an addition
        '400':
          $ref: '#/components/responses/400BadRequest'
        "404":
          description: "Order not found"
          
    # 7. Barista releases the Order
    delete:
      tags:
      - "Barista and cashier"
      description: Release the order
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted an order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/400BadRequest'
        "404":
          description: "Order not found"
          
    # 3. Cashier creates a Payment for the order
    #You are in order/, and for the order id you create a payment.
  /order/payment/{orderId}:
    post:
      tags:
      - "Barista and cashier"
      description: Cashier creates a payment for the order
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: Successfully created a payment for the order
        '400':
          $ref: '#/components/responses/400BadRequest'
        "404":
          description: "Order not found"
          
    # 6. Barista checks if the Order is paid
    get:
      tags:
      - "Barista and cashier"
      description: Checks if the order is paid
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
            properties:
              orderId:
                type: string
              paid:
                type: boolean
      responses:
        '200':
          description: Successfully returned an order
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId:
                   type: string
                  paid:
                   type: boolean
        '400':
          $ref: '#/components/responses/400BadRequest'
        "404":
          description: "Order not found"
  /order/status/{orderId}:
  
  # 5. Barista changes the status of the Order to being prepared
    patch:
      tags:
      - "Barista and cashier"
      description: Changes the status of the order to being prepared
      parameters:
        - name: orderId
          in: path
          description: ID of order
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                paid:
                  type: boolean
                  default: true
          #The status of the order can i.e. be changed to prepared, which will make it an open order, served or cancelled.
          #If a customer cancel the order, paid will also be changed to false as they will get their money back. This depends on how the database is structured.
      responses:
        '200':
          description: Successfully changed the status
        '400':
          $ref: '#/components/responses/400BadRequest'
        "404":
          description: "Order not found"
   
   # 4. Barista gets the list of all open Orders (only one order is available)
   # 8. Barista gets the list of all Open Orders (no order is available)
  /orders:
     get:
      tags:
      - "Barista and cashier"
      description: Returns a list of orders
      parameters:
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
      responses:
        '200':
          description: Successfully returned a list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          $ref: '#/components/responses/400BadRequest'
